### ISSUE TITLE
Error when loading data

### ISSUE THREAD

**Issue by mwfoster** [Integrative-Transcriptomics/OmicsTIDE#9]
Hi,

I'm getting the following error when I try to load the test data on a local install. Please let me know if you have any suggestions.

Note I have a similar issue when trying to load external data to the instance of OmicsTIDE on your website.

Thanks,

Matt

[2021-10-19 13:54:47,975] ERROR in app: Exception on /load_test_data_streptomyces [POST]
Traceback (most recent call last):
  File "C:\Matt2\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Matt2\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Matt2\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Matt2\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Matt2\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Matt2\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/OmicsTIDE-master/__init__.py", line 292, in load_test_data_streptomyces
    data['Comparison1'] = pairwise_trendcomparison(trans_m1152, trans_m145, 1, lower_variance_percentile, upper_variance_percentile, k, True)
  File "C:\OmicsTIDE-master\trend_comparison.py", line 110, in pairwise_trendcomparison
    ds1_file = preprocess_file(tmp_file1)
  File "C:\OmicsTIDE-master\preprocess_files.py", line 24, in preprocess_file
    init = pd.read_csv(input_file, index_col='gene', sep= ",")
  File "C:\Matt2\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Matt2\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Matt2\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Matt2\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Matt2\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File .\static\data\caseStudy_colnames\Transcriptome_M1152.csv does not exist: '.\\static\\data\\caseStudy_colnames\\Transcriptome_M1152.csv'
127.0.0.1 - - [19/Oct/2021 13:54:47] "POST /load_test_data_streptomyces HTTP/1.1" 500 -

**Comment by ThHarbig** [comment]
Hi,

thanks for reporting this and for using our tool. This Repo is an old version of OmicsTIDE, we did a reimplementation in this Repo: https://github.com/Integrative-Transcriptomics/OmicsTIDE2.0. In this Repo I recently fixed a bug with loading the second test data set. Are you using the latest version? Feel free to send me the files if you want me to assist you with loading local files!

**Comment by mwfoster** [comment]
I have tried that as well. Can repost there, but when I try loading in the “TEST DATA”,  I’m also getting an error. I have just been trying to load in your .csv files included in the package, either manually or through the “TEST DATA” option. Thanks, Matt

> ***@***.*** start C:\OmicsTIDE2.0-master
> react-scripts start

i ?wds?: Project is running at http://10.236.155.136/
i ?wds?: webpack output is served from
i ?wds?: Content not from webpack is served from C:\OmicsTIDE2.0-master\public
i ?wds?: 404s will fallback to /
Starting the development server...
Compiled successfully!

You can now view omicstide2.0 in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://10.236.155.136:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

Proxy error: Could not proxy request /load_test_data_bloodcell from localhost:3000 to http://localhost:5000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by ThHarbig** [comment]
I was able to reproduce the issue with a fresh local install on my machine. I fixed it by updating the python requirements file requirements.txt. It should work now if you do a fresh install with this file. Furthermore, I updated the Readme, since I forgot the command "npm install" (but I think you already figured this out). Let me know if there is further problems and sorry for the inconvenience!

**Comment by ThHarbig** [comment]
Note that the development version is a bit slower for big data sets than the production version. To run the production version you can run:
`npm run build`
`npm run server`
and access the app at http://localhost:5000/
